### ISSUE TITLE
FileSystemMonitorMicroService Unhandled Exception Error: System.TimeoutException

### ISSUE THREAD

**Issue by ladesigner1** [PacktPublishing/Hands-On-Microservices-with-CSharp#1]
Chapter 8: FileSystemMonitorMicroService

I receive this error message whenever I drop files into the test folder, as shown on page 151 in book:

Topshelf.Hosts.ConsoleRunHost Critical: 0 : The service threw an unhandled exception, System.TimeoutException: The operation requested on PersistentChannel timed out.

How to correct? Looking for a fix to this issue!

**Comment by suwarnarajput** [comment]
Hello team,


The reader should use the latest version of EasyNetQ.


Thanks and regards,

Suwarna




________________________________
